### ISSUE TITLE
https://collapseos.org/ is down

### ISSUE THREAD

**Issue by neauoire** [hsoft/collapseos#100]

**Comment by hsoft** [comment]
Whoa, I nearly let the domain expire! My provider didn't notify me of expiration. Whew! thanks for the heads up, website should be back soon.

**Comment by neauoire** [comment]
No problem :) If the site is entirely static, you could point the domain to a repository and host the website on github pages, it would also invite PRs to the documentation.

**Comment by hsoft** [comment]
Website is back for me. it should be back for everyone once DNS cache is invalidated everywhere.
