### ISSUE TITLE
Print the current value of the memory pointer in shell

### ISSUE THREAD

**Issue by dprentiss** [hsoft/collapseos#11]
Is there a way to print the current value of the memory pointer in shell? If not, would this be the appropriate behavior for mptr with no argements? Without arguments, mptr currently returns error 02.

Lovely project!

**Comment by dprentiss** [comment]
This is not likely to be addressed under the current scheme for shell parsing. Further discussion is at #17.

**Comment by vlaube-de** [comment]
this is now implemented by pull request #65
