### ISSUE TITLE
The  sega master system makefile is broken

### ISSUE THREAD

**Issue by Liorst4** [hsoft/collapseos#113]
Running the `Makefile` of `sms` on  a fresh clone of the repository yields the following error
```
 cc     ../../emul/stage.c   -o ../../emul/stage
/usr/bin/ld: /tmp/cclrg8gR.o: in function `main':
stage.c:(.text+0xaf): undefined reference to `emul_init'
/usr/bin/ld: stage.c:(.text+0x126): undefined reference to `emul_step'
/usr/bin/ld: stage.c:(.text+0x16e): undefined reference to `emul_deinit'
/usr/bin/ld: stage.c:(.text+0x178): undefined reference to `emul_printdebug'
collect2: error: ld returned 1 exit status
make: *** [<builtin>: ../../emul/stage] Error 1
```

Workaround:
Running the `Makefile` in `emul` before running the `Makefile` in `sms` fixes it.

The `Makefile` of `sms` should call the `Makefile` of `emul` if some targets are missing

**Comment by hsoft** [comment]
Yeah, those makefile should be a bit more newcomer-friendly, fixing.
