### ISSUE TITLE
Visual Editor: Inserted text at the end of the line might be truncated

### ISSUE THREAD

**Issue by Liorst4** [hsoft/collapseos#114]
If the cursor + the size of the inserted text is larger the line length (64), the inserted text is truncated.

Steps to reproduce

```forth
125 LOAD
VE
```
input in the visual editor
```
999 g
63 l
I ABC<CR>
```
Results in only `A` being written

**Comment by hsoft** [comment]
Yes, it's by design. The user of the OS is expected to be aware of technical limitations due to focus on compactness.

**Comment by hsoft** [comment]
To be clearer: we have to approach this project by letting go of our modern expectations. If we meet those expectations, then the project becomes too complex to be viable. As a though experiment (and exercise), I invite you to think of a proposal for this problem and then look at the code and see how you'd implement it. Unless I've overlooked something, you'll quickly see that complexity piles up *very fast* for addressing this seemingly simple problem.
