### ISSUE TITLE
Planning on leaving Github

### ISSUE THREAD

**Issue by hsoft** [hsoft/collapseos#127]
Although not the root motivation for creating Collapse OS, a profound contempt of modern technology, and modern software in particular, certainly goes hand in hand with it.

This contempt of course prompts me to keep my modern environments tidy. Github is the only reason why my main development environment, a minimal OpenBSD setup, still has a modern web browser on it. I'd like to get rid of it.

There's the github cli app, but last time I checked, access to the web interface was still needed, if only for setting up cli authentication.

I've been planning on getting off Github for a little while now, this ticket is my advance notice.

## What about issues?

I'm thinking of doing away with issue tracking and set up a mailing list instead. I don't even want to bother with maintaining a mailing list management software, so I was thinking of manually managing email aliases. I'm expecting low subscribers volume, so it should be easily manageable.

## From git to RCS

This move prompts me to ask myself "why am I using git?". With github, git allows for easy collaboration, but there aren't that many collaborators anyway. I'm mostly using git because I think that having access to Collapse OS' commit history helps "grokkability" a lot. That's why I use git.

Git in OpenBSD is a port. Git is quite big, making me think it's overkill. RCS is built-in and gives me what I want: revision logs.

Therefore, I'm also planning on using RCS instead of git. I'd upload weekly snapshots of the repo on collapseos.org.

## Collaboration?

Will this make collaboration harder? To quote Obi Wan, "from a certain point of view".

Collapse OS already requires a certain amount of dedication to effectively work on it. Would having to subscribe to a ML and send patchsets through mail turn away some people? Maybe, but I'm thinking it's not going to turn away the dedicated type, so the project might end up not losing much. It would certainly help with "drive-by PRs" annoyance.

## Timeline

This move isn't for now, but what used to be a fuzzy idea in my head is now a definite plan. I personally got rid of the maintenance burden of all other repos I used to maintain, so there's no blocker any more.

Feedback welcome.

**Comment by MasterOfTheTiger** [comment]
You may be interested in SourceHut. It is made to interact nicely with email (mailing lists, patches, etc.), and the front end is made to be as simple as possible, not requiring JavaScript. It makes the traditional git workflow even more convenient.

It is at least worth looking into.

https://sourcehut.org

**Comment by hsoft** [comment]
Interesting, thanks for the tip. It might actually be a very good solution, or if it isn't, a good way to transition to my RCS setup. No frills, I like the style. @ddevault is prolific :)

**Comment by ddevault** [comment]
Please let me know if you need any help with sourcehut :) I think you would find it better than abandoning git; even after the collapse of civilization I think git will be in my toolkit.

**Comment by hsoft** [comment]
Sourcehut is really nice. Its design look very much like what I'd spec out if I was asked what I want, and I didn't even have to bother asking myself what I want! So far, it seems to work well with Lynx. Good job! moving over to https://git.sr.ht/~vdupras/collapseos...

**Comment by ddevault** [comment]
Glad you like it! Be sure to [create a project](https://sr.ht/projects/create), too.

**Comment by schierlm** [comment]
Do you know if SourceHut is (planning to) participate in the Software Heritage project? If not, it may be prudent to mirror the project to a platform that does. It does not have to be you to set that up, and considering that (for example) GitHub actions support to push to their own repo, it could even be a no-touch process.

Also, I can find the new project feed but no RSS link for it? as I have a few hundred RSS feeds in my Thunderbird, I don't want to miss CollapseOS commits that way. And I prefer RSS to having a `-commits` mailing list where I need filter rules and that will clutter my normal email inbox if I access it via webmail.

**Comment by ddevault** [comment]
They haven't reached out to us, but we would be open to working with them.

RSS feeds are planned for the project feed, but you can access RSS for the commits now:

https://git.sr.ht/~vdupras/collapseos/log/rss.xml

**Comment by schierlm** [comment]
As far as I understand it, from a technical side it would require you to invoke the https://archive.softwareheritage.org/api/1/origin/save/doc/ API for every new repository once it received its first commit (does not need to be instantaneously, just no repository should be forgotten). You'd also need to get your software site whitelisted (otherwise they will do some manual checks for every repository you submit) but I don't know exactly how that process works (they do have a mailing list or an IRC channel, though: https://www.softwareheritage.org/community/developers/)

**Comment by ddevault** [comment]
I don't have the time to work on it myself - but if someone writes up a technical proposal and submits it to sr.ht-dev, I can look it over for any potential issues, then merge the necessary patches (sourcehut is open source, after all).

**Comment by hsoft** [comment]
Alternatively, someone could simply setup a github mirror of the sourcehut and it would be picked up, no?

**Comment by ddevault** [comment]
Whichever works for you :)

**Comment by jodavaho** [comment]
I commonly push release candidates to github (e.g., github.com/nasa/mosaic ), but otherwise manage day-to-day development on an internal github @nasajpl 

This workflow might work for you, with infrequent-but-significant pushes to github, but day-to-day development on sr.ht

**Comment by jtolio** [comment]
Seems like CollapseOS would be great to have in https://archiveprogram.github.com/

**Comment by mininmobile** [comment]
On the topic of the Archive Program, (if I remember correctly) they archived every active repository with commits within the past 2 months. I'm pretty sure this repo - or at least a version of it - is *probably* safe. I don't think a list of every archived repository is available though so there is no confirmation on whether it is actually safe or not :(

**Comment by hsoft** [comment]
I've also moved away from SourceHut in favor of self-hosted tarballs (with RCS, as per my original plan) for the reasons outlined at https://lists.sr.ht/~vdupras/collapseos/%3C3094b57c-000c-4893-937f-b5d699a4aeb2%40www.fastmail.com%3E

**Comment by ddevault** [comment]
For what it's worth, the email issue discussion petered off, but it stayed in our todo lists and a patch addressing it was applied yesterday morning.

**Comment by hsoft** [comment]
@ddevault to be clear, I didn't want to imply that the SourceHut team wouldn't address this issue in a timely manner, but only that I was in some kind of untenable position where I couldn't apply pressure on you and I didn't care enough of SourceHut's code to dive into it myself.

**Comment by ddevault** [comment]
Makes sense.
