### ISSUE TITLE
What about smartphones?

### ISSUE THREAD

**Issue by Endogen** [hsoft/collapseos#2]
First of all, i don't get any of this. I was a user of moneyGuru and loved it and i kind of got here - somehow. Since you wrote about tech that would be used after an apocalypse. What i think is that smartphones would be scattered all over the place. wouldn't you think? Wouldn't be ARM the way to go?

**Comment by hsoft** [comment]
There are tons of computer around, many of them functional. They will be for decades. But they can't be repaired and we can't make new ones. Collapse OS is for when those computers die.
