### ISSUE TITLE
Computer and Circuit Schematics 

### ISSUE THREAD

**Issue by NoahGWood** [hsoft/collapseos#22]
I'd like to help design some computers, is this something that should go in it's own repository or should it be added to this one?

Picture somewhat related:
single qubit quantum computer I designed

![20191003_130806](https://user-images.githubusercontent.com/26890744/66538548-aa735a00-ead9-11e9-824c-0626be27ac1e.jpg)

**Comment by hsoft** [comment]
I'd say it would go in its own repository. Eventually, we could think about creating a kind of "starter pack" that includes several nicely thought out designs packed up together, but I think it would be a bit premature at this point.

**Comment by keithstellyes** [comment]
My gut reaction is that explicit designs seem like they would be a bit antithetical to the whole "computer built from cobbled together" idea, so might be a good thing to keep in mind (make sure they're flexible?)

**Comment by NoahGWood** [comment]
@hsoft
That was kinda my thinking too

@keithstellyes
Well there are some things you will need no matter what, like ROM and RAM.

Schematics can be specific or general, I'm envisioning a printable book that people can store containing instructions on everything from transistor and capacitor fabrication from raw materials, to logic gate construction, scavenging components, and other practical information that would be vital in a post collapse world.

With that said, a good starting point would be simple designs based on existing chips that are widely available.

**Comment by NoahGWood** [comment]
I've created a repository for post-collapse hardware, currently working on a basic Z80 computer design. Closing this issue
https://github.com/NoahGWood/collapseSchema
