### ISSUE TITLE
Contributing.md?

### ISSUE THREAD

**Issue by QuercusFelis** [hsoft/collapseos#25]
Given the recent attention this project has been getting, perhaps a contributing.md could help establish a common formatting standard for contributors and make more clear what kind of contributions the project needs right now.

**Comment by keithstellyes** [comment]
Not a bad idea, but good to check out: https://collapseos.org/roadmap.html

**Comment by QuercusFelis** [comment]
I'm aware of the roadmap, there just seems to be a lot of confusion with new comers not checking that before trying to contribute. Took me a while to realize where the roadmap was, too. With assembly though I think a strict formatting convention and an easy way to follow it is crucial.

**Comment by hsoft** [comment]
It is clear now that a Contributing.md file is very necessary. Expectations are evidently not clear enough.

I was taken by surprise by how my initial post went viral and I didn't expect this kind of participation. I am of course very pleased with it and I hope to be able to channel this creativity properly. This project used to simply be organized as my own little sandbox.

Writing up this file is my first priority with regards to this project.
