### ISSUE TITLE
Arduino

### ISSUE THREAD

**Issue by imFixMix** [hsoft/collapseos#26]
Can CollapseOs run on an Arduino board?

**Comment by keithstellyes** [comment]
Arduino boards are all ARM processors, not Z80s.

Arduinos are a lot more powerfu, thoughl ;), could honestly probablaly run a Z80 emulator on it though (https://github.com/redcode/Z80 for example is a great Z80 emulation library)

**Comment by QuercusFelis** [comment]
CollapseOS is written in z80 assembly for z80 processors. Arduinos use ARM microcontrollers which run on the ARM and Thumb instruction sets. They are essentially functionally incompatible without emulation overhead.

**Comment by hsoft** [comment]
As a complement to other reply, see https://old.reddit.com/r/collapse/comments/dejmvz/collapse_os_bootstrap_postcollapse_technology/f2wgxq9/ to see why AVR is unsuitable. That being said, I really like AVR and it will be, of course, possible to program an AVR chip from Collapse OS.

**Comment by hsoft** [comment]
Oh, by the way guys. Arduino is mostly AVR-based, not ARM (unless they've changed things recently)

**Comment by QuercusFelis** [comment]
There are a good number of arduinos using ARM, I did completely forget about AVR though, haha.

**Comment by imFixMix** [comment]
> Arduino boards are all ARM processors, not Z80s.
> 
> Arduinos are a lot more powerful, though ;), could honestly probablaly run a Z80 emulator on it though (https://github.com/redcode/Z80 for example is a great Z80 emulation library)

Thats good perversion

**Comment by imFixMix** [comment]
In general, easier to write new system, special for AVR-platform
