### ISSUE TITLE
Tests?

### ISSUE THREAD

**Issue by keithstellyes** [hsoft/collapseos#27]
I was thinking of starting some testing, would there be interest? Willing to take ownership there.

I'm thinking the best way of doing this is using a simple Z80 emulation library, seems like it would be good of keeping track of what _exactly_ is happening. Also help show some minimalistic recipes.

Thoughts? Wanted to see if that'd be of interest before I jumped the gun. Thanks!

**Comment by hsoft** [comment]
There's already a test suite in `tools/tests`, but it's a bit light and is mostly focused on zasm. I was thinking about improving test coverage to userspace app by developing some kind of shell "replay and make sure there no diff in the output" mechanism.

But anyways: sure, more tests is always good. Take a look at the existing suite, I'm all ears for improvements.
