### ISSUE TITLE
Basic support?

### ISSUE THREAD

**Issue by gusmanb** [hsoft/collapseos#31]
Targeting old machines using Z80 processors adding a Basic interpreter would be a logic step. It was implemented in nearly every single Z80 computer, is a very easy to learn languaje and even without a real manual anyone can understand it as it's like talking to the machine in english.

Is this on the roadmap?

There are some open source implementations like TinyBasic that are ideal for this, TinyBasic per example is only 2Kb once compiled and is easily extended.

**Comment by hsoft** [comment]
As I wrote in another ticket, yes. Also, tinybasic is public domain so licensing is fine. However, those old basic follow TASM's syntax and have to be translated to zasm. They also have to be plugged in Collapse OS' IO routines. But is that's something you'd like to do, please go ahead, it would be a nice userspace addition.

**Comment by keithstellyes** [comment]
See: https://github.com/hsoft/collapseos/issues/7

**Comment by hsoft** [comment]
(I feel like my [roadmap's rigidity](https://collapseos.org/roadmap.html) is loosening by the minute though. Oh well :) )

**Comment by gusmanb** [comment]
I will check ZASM, I have never used it :)

**Comment by hsoft** [comment]
Of course you haven't: it's Collapse OS' builtin zasm dialect (I say this because you seem like someone who's about to google "zasm").

**Comment by keithstellyes** [comment]
Wish I had seen that Roadmap, will have to look at that :)

**Comment by gusmanb** [comment]
@hsoft yep, you nailed it, I was looking for ZASM as I remember there's a Z80 compiler named ZASM, but luckily I checked the tools folder before doing nothing and found the readme, so everything is ok :)

I'm porting it, you can check my advances here: https://github.com/gusmanb/tinybasic/blob/master/TinyBasicCOLLAPSEOS.asm
