### ISSUE TITLE
[request] Public Wiki

### ISSUE THREAD

**Issue by NoahGWood** [hsoft/collapseos#32]
Is there any chance you can enable the wiki for community documentation of the OS and kernel? #8

**Comment by NoahGWood** [comment]
Wouldn't be a bad idea to create an IRC or similar either so we're not flooding the git with issues

**Comment by QuercusFelis** [comment]
See https://github.com/hsoft/collapseos/tree/master/doc for documentation

**Comment by NoahGWood** [comment]
@QuercusFelis 
Yeah, I know it's there, I was thinking about a wiki or similar though, something you can talk more in-depth and long format about the various components of the system, using something like Sphinx wouldn't be a bad idea either but with the wiki you can also set it up so you don't need to merge every single edit done to it

**Comment by hsoft** [comment]
I'm unfamiliar with Github's wiki permissions and I don't dare deface someone else's project. Aren't project wiki public by default? Can't anyone already create pages on the project's wiki?

**Comment by hsoft** [comment]
As written in #8 :

> This is an interesting subject, a fundamental one: what kind of information can we put together to maximize the chances for a given post-collapse community to bootstrap itself using the tools at hand?
> 
> Of course, the documentation as it is is grossly inadequate, it needs improvement.
> 
> I think that the pull request model of github is too rigid to spur collaboration, but at the same time, I also think that public wikis lack focus.
> 
> What about brainstorming in a public wiki and then transfer this to `doc/` through the PR model when we think we have something?

**Comment by schierlm** [comment]
@hsoft In older repositories, wikis are public by default. In more recently created ones, only collaborators can edit the wiki. In either case, you will find the checkbox to change this as "**Restrict editing to collaborators only**" in the project settings.

**Comment by hsoft** [comment]
I hadn't noticed that checkbox. Thanks. The wiki is now free-for-all. I'll create a guiding home page in the coming days, but if someone wants to beat me to it, go ahead :)

**Comment by AsherGomez** [comment]
Went ahead and put the info from `/docs` to the Wiki.

**Comment by octave-syndicate** [comment]
> Wouldn't be a bad idea to create an IRC or similar either so we're not flooding the git with issues

I've created an IRC channel on freenode. Should be able to access it at : 

irc://irc.freenode.net/collapseos

@hsoft If you or someone you nominate would like to be op on the channel just let me know.

**Comment by hsoft** [comment]
The wiki was there for a while now and resulted in nothing good. I don't think it's a good way of producing a reliable documentation for the project. Removing it.
