### ISSUE TITLE
Running make inside tools/emul fails.

### ISSUE THREAD

**Issue by libjet** [hsoft/collapseos#34]
Hello, when running make in collapseos/tools/emul I get the error:
`make: *** No rule to make target 'libz80/z80.c', needed by 'libz80/libz80.o'.  Stop.`
uname -a output: Linux ARCH-PC 5.3.1-arch1-1-ARCH #1 SMP PREEMPT Sat Sep 21 11:33:49 UTC 2019 x86_64 GNU/Linux

**Comment by keithstellyes** [comment]
When you do git clone you need to do

git clone --recursive because libz80 is a submodule

**Comment by libjet** [comment]
Ah thanks, I'm not too knowledgable about git but this fixed the issue.
