### ISSUE TITLE
The question of assistance to the project

### ISSUE THREAD

**Issue by StasToken** [hsoft/collapseos#36]
write in Readme,md crypto-wallets where you can be assigned, please, I myself am a programmer but I can’t join you yet due to busyness, but with pleasure I will support your project financially.
Many give of course not can, but I think you other participants, too, can support listing some means.

**Comment by hsoft** [comment]
Thanks for your offer, but money isn't a motivation for me and I believe that involving money in an open source project tends to taint it, so I prefer to keep it out.

It's alright to not participate, you don't need to. Moral support is sufficient. Thanks for your moral support.
