### ISSUE TITLE
Audio Networking?

### ISSUE THREAD

**Issue by nothingismagick** [hsoft/collapseos#37]
Coming from the side of hardware hacking and circuit bending, there are a couple of components that are also prolific: microphones and speakers. I think it would be a good addition to follow the audio-networking approach of gnu-radio. Combined with netcat - and you have a local network. Attach to a ham setup and you're global. Of course its slow - but personally I am not enthusiastic about wiring up 10G transponders to a z80.

https://hackaday.com/2014/02/19/audio-networking-with-gnu-radio/

> Normally I hate doing this kind of "drive-by feature request" - but I have zero assembly skills and can neither scope the amount of work involved nor contribute in any really meaningful way.

**Comment by gusmanb** [comment]
It's a good idea, but I think to use something more standard and used during decades would be better.
Audio data enconding was the norm on the 80's, we stored data in regular tapes as it was cheap and available to anyone. One of the most widely encoding used was the [Kansas City encoding](https://hackaday.com/2018/10/07/reading-old-data-tapes-the-hard-way/), it's easy to implement and it needs only basic components to encode/decode it.
Also, this format is already valid for broadcasting but usually for packet radio the [AX.25 protocol](https://www.tapr.org/pr_intro.html) developed in 1970 was the most used.

**Comment by nothingismagick** [comment]
Ok - well, the only issue I have with that is that in the relatively dangerous environment this scenario is planned for, being that loud could be dangerous. I would prefer the subsonic approach and not alert any predators (human or otherwise) that I am broadcasting my daily report... But AX.25 is a good idea.

**Comment by hsoft** [comment]
Sorry if expectations weren't clear initially. But since PR #53, they are: Collapse OS' only goal is to program microcontrollers. Networking isn't on its radar. That being said, if Collapse OS' code can be useful for a networking project, please don't hesitate to use it.
