### ISSUE TITLE
Optional package with basic science information

### ISSUE THREAD

**Issue by heronz** [hsoft/collapseos#38]
Hello all!  
  
So I was wondering, since this is a project with the apocalypse in mind, it'd be nice to have some information about the basics of science and the knowledge we've built so far stored in a simple way so you could bring together with the most basic machine.
  
Something like, ways to start a fire, ways to make a battery, and a path to evolve again from the scraps of society.  
  
Maybe include a optional package to something like this:
[Link](https://en.wikipedia.org/wiki/Wikipedia:Database_download#English-language_Wikipedia)  
```
pages-articles-multistream.xml.bz2 – Current revisions only, no talk or user pages; this is probably what you want, and is approximately 14 GB compressed (expands to over 58 GB when decompressed).  
```
If I'm posting this in the wrong place, could you tell me where I should post ideas like these?  
Really liked the project, keep up the good work!

**Comment by keithstellyes** [comment]
It would probably be best to find something in plaintext that isn't like HTML or XML or something.

Project Gutenberg has simple plaintext files that would be good for this purpose but TBH it's already possible by just `wget`ting the desired texts and placing it in `cfsin`.

For viewing it one can use `ed`

**Comment by vlaube-de** [comment]
The maximum filesize for cfspack is about 64kb right now, so there is still some work left until you can use collapseos as an ebook reader.

**Comment by keithstellyes** [comment]
http://www.gutenberg.org/ebooks/345

Yeah these far exceed 64kb, even with EPUB which would be incredibly difficult to implement here. Probably want to implement DEFLATE here

**Comment by QuercusFelis** [comment]
This is probably best put in its own separate repository. I believe that education and information while important is perhaps at best parallel to the creation of a minimalist operating system. It is, however, a good idea for a companion project and I don't want to discourage anyone from pursuing this further.

**Comment by keithstellyes** [comment]
An e-reader of sorts does seem handy, but arguably that would be redundant with `ed` if shooting for minimalism. 

If someone wanted to set-up their little e-reader CollapseOS machine, no reason you couldn't cook up a simple script on the non-CollapseOS system to take the large .txt files and break them up

**Comment by NoahGWood** [comment]
You're better off just setting up your own home server and downloading a copy of Wikipedia to be honest

**Comment by keithstellyes** [comment]
> You're better off just setting up your own home server and downloading a copy of Wikipedia to be honest.
> 
> Which is to say, not something the Z80 would be useful for.
> 
> I've done it before, it's not difficult, there's plenty of guides out there on how to do it.

That's cheating though, isn't it? If you can just use a home server, why have this system at all?

**Comment by jodavaho** [comment]
> That's cheating though, isn't it? If you can just use a home server, why have this system at all?

To leave behind when it breaks and your understanding is stretched too far ...  for an information archeologist to recover and boostrap back into existence.

**Comment by hsoft** [comment]
Sorry if expectations weren't clear initially. But since PR #53, they are: Collapse OS' only goal is to program microcontrollers. Document storage isn't on its radar. That being said, if Collapse OS' code can be useful for another project, please don't hesitate to use it. I tend to think that paper is a nice technology...
