### ISSUE TITLE
Ti-83/84+ asm macro support in compiler

### ISSUE THREAD

**Issue by Izder456** [hsoft/collapseos#39]
will the included compiler support Ti-83+ macros for running system code such as: `bcall(_clrscreenfull)`

**Comment by keithstellyes** [comment]
I personally don't see why it wouldn't, depending on whoever is doing that initial TI-84 recipe

**Comment by Izder456** [comment]
right now I'm trying to write the recipe for Ti-83/84+. Just so you know I'm trying to learn z80 Asm with this project and hope I can help

**Comment by keithstellyes** [comment]
Just my two cents but I think it would be best to have it eventually, but should focus on baby steps, like, starting out with a prototype that boots and has a prototypical way of doing input, doing a PR, getting that merged, then going forward.

Don't wanna do that thing every dev has done at some point and submit a massive PR and just get told "break it up" or told to restructure it

**Comment by Izder456** [comment]
ok that's cool with me. What file mimetype do you think should be bootable? a `boot.bin` or a `boot.z80`. 
Into other words what file is output when you compile?

**Comment by hsoft** [comment]
In experiments I've done on the TI-84+, uploading a new OS to the calculator seems to overwrite TI's OS. These useful routines have to be reimplemented.

I think technical challenges regarding the TI-83 and TI-84 should be discussed in #41. Closing.
