### ISSUE TITLE
Ti-Keyboard support when plugged into Ti-83/84+

### ISSUE THREAD

**Issue by Izder456** [hsoft/collapseos#40]
Should it be a good idea to add Ti-Keyboard support in the Ti-83/84+ recipe? I will try to do so if hsoft approves.

**Comment by keithstellyes** [comment]
Kinda repeating what I said on #39, this would be a good idea but I think we should wait until we're booted and running on the TI before we worry too much about this

**Comment by hsoft** [comment]
As with #39, closing in favor of #41
