### ISSUE TITLE
Why GPL ?

### ISSUE THREAD

**Issue by malaire** [hsoft/collapseos#48]
Why is this project using GPL 3.0 license and not e.g. BSD license?

GPL 3.0 as text is 34 kB. Whenever you clone the OS to someone you must include this additional burden. Not to mention the burden of understanding the huge amount of legal jargon.

In comparison e.g. BSD license is under 2k and much easier to understand.

EDIT:
I forgot to say the most important point: GPL requires including source code. In post-collapse world that is extremely stupid thing to require.

What if your friend needs copy of CollapseOS and doesn't have enough space to include whole source code, and also doesn't even need the source?

With GPL you must say to your friend: Sorry, for legal reason I can't give you just the binary.

With better license like BSD you can.

**Comment by Clanmaster21** [comment]
If we're going for smallest space then I'd suggest WTFPL, that's only like 475 bytes, and it doesn't get much easier than that to understand. Unsure how much it holds up in a legitimate setting though.

**Comment by malaire** [comment]
I forgot to say the most important point: GPL requires including source code. In post-collapse world that is extremely stupid thing to require.

What if your friend needs copy of CollapseOS and doesn't have enough space to include whole source code, and also doesn't even need the source?

With GPL you must say to your friend: Sorry, for legal reason I can't give you just the binary.

With better license like BSD you can.

**Comment by keithstellyes** [comment]
Software copyright is definitely a legal gray area in a post-apocalyptic world.

I think GPL3 is just you have to make it available, right?

**Comment by malaire** [comment]
Yes, source must be available with GPL3. Nowadays it's simple to just say that you can download source from Internet if you want, so it doesn't need to be included. But in a world where there is no Internet that won't work.

Actually I should've checked the actual [GPL3](https://www.gnu.org/licenses/gpl-3.0.en.html) text, which says in Section 6 (emphasis mine):
> You may convey a covered work in object code form under the terms of sections 4 and 5, provided that you also convey the machine-readable Corresponding Source under the terms of this License, in one of these ways:
> ...
> b) Convey the object code in, or embodied in, a physical product (including a physical distribution medium), accompanied by a **written offer**, valid for at least three years and valid for as long as you offer spare parts or customer support for that product model, to give anyone who possesses the object code either (1) a copy of the Corresponding Source for all the software in the product that is covered by this License, on a durable physical medium customarily used for software interchange, **for a price no more than your reasonable cost of physically performing this conveying of source** ...
> ...

I believed that source must be available for free, but actually it is allowed to give a written offer instead, to provide source with a reasonable price if requested. (And in post-apocalyptic world such a reasonable price might well be somewhat high.)

I'll close this issue, as I was wrong about this.

**Comment by hsoft** [comment]
This project started out as BSD, but when libz80, which is GPL, became a central part of the project, I had to relicense.
