### ISSUE TITLE
Basic walkthrough on CollapseOS usage (was: How do you cat a file?)

### ISSUE THREAD

**Issue by jes** [hsoft/collapseos#54]
I'm confused about how you can inspect the contents of a file.

For example at https://gistcdn.githack.com/schierlm/96d84f0e98861f7d35965e3b91d8d31c/raw/5da8db083140a2b9b955a549c212220ddf2f074e/index.html there is a file called readme.txt, but I have no idea how to send it to the console using the builtin file manipulation tooling?

**Comment by jes** [comment]
Likewise, `ed` could possibly do with some documentation as I can't figure out how to use it at all.

**Comment by hsoft** [comment]
Documentation on shell usage could use some improvements yes. If you volunteer to do the writing, I'd be glad to supply you with missing information.

There is no `cat` equivalent in the shell. `ed` is the way to view/edit text files.

**Comment by jes** [comment]
Yes, I'd gladly write some documentation.

I think possibly a walkthrough showing how to make changes to & build CollapseOS from within CollapseOS would be a good start, and once there is ATmega tooling available, a similar walkthrough showing how to make a "blinky LED" program and upload it to an Arduino.

**Comment by jes** [comment]
Why does `zasm` need you to pass it block device numbers, when `ed` is capable of dealing with filenames?

**Comment by hsoft** [comment]
legacy (`ed` is more recent than `zasm`). but also, block devices are more flexible. For input, there isn't much of a point to keep block device ID argument, we could change it to filename, but for output, I can imagine the ability to target a raw device to be very useful on machines with tight resources.

**Comment by jes** [comment]
For my own reference: the way to cat a file is:

```
ed file
:1,p
:q
```

**Comment by hsoft** [comment]
I believe that this point has now been addressed and that documentation on block editing is sufficient.
