### ISSUE TITLE
Emulated FS doesn't work if initial FS has no files

### ISSUE THREAD

**Issue by jes** [hsoft/collapseos#55]
It gives ERR 05 when you try to `fls`, and it also does the same even after you create a file:

```
$ rm cfsin/*
$ shell/shell
Initializing filesystem
Collapse OS
> fls
ERR 05
> fnew 1 test
> fls
ERR 05
```

**Comment by jes** [comment]
Seems to load zeroes off the disk as expected, apart from a surprise "ERR 02" when seeking to byte 0.

```
> bsel 0
> seek 0
ERR 02
> mptr 8000
8000
> load 32
> mptr 8000
8000
> peek 32
0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
```

**Comment by jes** [comment]
@hsoft The reason the empty fs doesn't work is because fsIsValid checks for the "CFS" header, and cfspack doesn't produce such a header if there are no files.

I've fixed it in https://github.com/jes/collapseos/commit/63826c3c729e8c327f2d3a528365db4bb69c6033 which is now part of my other pull request, but we can figure out how to separate it into a separate one if you prefer.

I don't know whether you are happy having an empty block at the end of every filesystem produced by cfspack. From what I've observed, the actual CollapseOS fs implementation writes an empty block after the end of the filesystem anyway, so this is probably not a problem. Or, if it is a problem, it's a problem in the CollapseOS fs implementation as well.

**Comment by schierlm** [comment]
@jes: Does that fix work as intended? `zasm.sh` concatenates multiple CFS filesystems, and as I see it, this would break if the first one had an empty block at the end. (To be honest, I did not test it with your pull request applied, just from looking at the code).

**Comment by jes** [comment]
Ah, you're right. This breaks zasm.sh.

I'll note that the actual CollapseOS kernel also writes an empty block at the end of the filesystem, but I don't really know the best way to fix this. Are we just saying that CollapseOS doesn't support empty filesystems?

**Comment by hsoft** [comment]
It's not that Collapse OS doesn't support empty filesystems, it does. It's `cfspack` that doesn't support writing out empty filesystems. This is only a problem in the emulated shell and won't really be a problem in actual situations.

What we could do instead of fixing `cfspack` would be to add a check in `shell.c`. If `cfsin` is empty, spit an empty CFS instead of calling `cfspack`.

**Comment by hsoft** [comment]
(or even just if the command's result is empty)
