### ISSUE TITLE
This project and the idea behind deserve a Hollywood movie

### ISSUE THREAD

**Issue by claudix** [hsoft/collapseos#6]
Today I've stumbled upon this project and I have to say that I have fallen in love with it and the idea behind. I remember when I was 9 that my dad started to show me listings of his Z80 programs he wrote back then when he was starting his company. 30 years later I'm taking over him after have programmed dozens of embedded systems based on different CPUs (among them, the successor eZ80). Reading your ASM listings just brought me really nice memories and I'm really excited about it. I have starred your project to remind me that if I have the time and a good idea to collaborate, I will not hesitate to contact you.

Congratulations for such a cool project!

**Comment by agsb** [comment]
As I, back to 70s green letters terminal

**Comment by pinacoelho** [comment]
@hsoft - I propose that this issue be left open until we get that Hollywood movie. :-)

Note to self: Fix the Spectrum and get the Timex FDD3000 out of storage ...

**Comment by hsoft** [comment]
Only if it stars that guy from the Hackers movie (I wouldn't say no Angelina either...) and that they pound furiously on their post-apocalyptic cobbled up keyboard to make a wind turbine come back online while the camera sweep around them.
