### ISSUE TITLE
Getting the software on bare metal

### ISSUE THREAD

**Issue by Allisontheolder** [hsoft/collapseos#74]
The assumption is: 
*You have a z80, 32K ram and up to 32K rom(eprom/eeprom/flashrom) and know how to 
  trick the rom to be at the high end of memory, if needed,
*A serial device such as Z80 DART/SIO or other uart.  And some kind of terminal, for now a PC.
*Clock is assumed to be reasonable not less than 2mhz and likely 4 or faster if the part can do it.
* Power supplies a good source of 5V and maybe other voltages as needed.
* Other things like capacitors, resistors, LEDs, Wire, Solder, hand tools...

The minimal Grant Searle system qualifies.
Also a file system is not even on the horizon as there is no mass storage.

The question is how do you bring that up so you can use it to develop your code?

Bottom line is that eprom/eeprom/flash has to contain some software.  The usual is a minimal 
monitor like Dunfields or one of many others.   That allows basic communications like loading 
a program and debugging to some level and uploading the result.

The chicken and the egg:
There is a but wait, we need a programmer to get that initial code in there.  The old school way
was toggle switch front panel but that eats ICs and switches and LEDs and often more complex 
(more circuitry even if simple) than the cpu.

We do not initially need a lot of eprom 1k is adequate.

Its possible with simple switchs and a bare Eprom/EEprom (flash has timing constraints 
faster than human) to program it.  As someone that has done this you only want to do it once.
Its very time consuming and error prone.  A PC makes this easy if you have one, and a 
programmer for it. If you don't its as they say, a problem.  Based on available resources 
it can be a significant or minor nuisance.  for now we are not so reasource constrained.

A Atmel atmega 328P is a good tool for making an eprom programmer, better if EEprom.

Once that exists and runs a good thing would be to add an eprom/eerpm programmer 
to the minimal system.  A great time saver error reducer.

We can go on  from here or consider other ways.  Are we constrained to what we can salvage 
in 2031?    Salvage is often not helpful for programmable devices as often the are one time programmable (OTP).

Allison

**Comment by hsoft** [comment]
For reference, the basic RC2014 recipe addresses the eeprom "chicken and egg" problem by suggesting a makeshift arduino based writer https://github.com/hsoft/collapseos/tree/master/recipes/rc2014 . But of course, the more kind of recipes we have to solve that chicken-ang-egg problem, the better.

**Comment by hsoft** [comment]
> Once that exists and runs a good thing would be to add an eprom/eerpm programmer
to the minimal system. A great time saver error reducer.

This already exists: https://github.com/hsoft/collapseos/blob/master/recipes/rc2014/eeprom/README.md

**Comment by Allisontheolder** [comment]
What if you don't have one?  Or have built one from the scrapbox up?
oh right you need to put code in the eprom.
It is a solution but.... 
As an existing solution, only if you buy one.  (Not knocking it as its pretty slick )
It falls to OK use this rather than PC based.

I could easily use the SDK85, but I have one and your can't buy one though
so that goes nowhere to solve someone elses problem.
You can easily make a SDK85, but then you need Tomyprom to load a 8755 eprom.
Or if your PC has a parallel port one of the programmers for that  and so on.

Generally tomyprom is the easy cheap way out as the parts are small coin and 
a Uno/nano Arduino is cheap and the software free. 

  https://github.com/beneater/eeprom-programmer

There are also ideas that are not RaspberryPi [if I have a Rpi why a z80!] of making 
your own terminal some of his are interesting.

That would allow getting code into the system.

No one said bootstrapping anew iron was easy.  Having done it at least a few 
times for all the major cpus and a few odd TTL ground up designs it gets 
easier with money and current tech.

Allison

**Comment by Allisontheolder** [comment]
While I initially discounted a front panel that is a viable solution as then rom 
in any form is not required.  That has been the first order bootstrap approach 
since they stopped hard wiring programs.

**Comment by Allisontheolder** [comment]
Using a the BASIC Grant Searle hardware design.

Only 2/4/8K ram at D000h (can be reqired for else where later.
Eprom at 8000h
Ram at (2k is enough)  0000

Minor changes... use 8K Eprom (27C64) as those only  need VPP 12.5V on pin1 to program.
adding a oneshot on the Z80 /Wait to hold the CPU (freeze address and data) for 1MS.

Minor jumper changes or parts swpaping can be used ot get ram/eprom where needed

Add front panel minimal that requires only 10 switches.  Basicly stimulating the Z80
HOLD (DMA logic) and subbing in a address and data from sequential counters.
The switches would be reset (cpu and DMA counter), load byte, 8data.  Leds for 
address and data would be useful (that adds three octal buffers (244, 5xx series).

Why not EEprom?  In scrap and salvage I've see Eproms and Rams are normally 
found around Z80s along with other useful parts.  EEproms, rare.

What My rather extensive parts bins can supply is largely meaningless, same for 
what I can buy.    The assumption is the world and supply chains are chronically 
broken as assuming time and money were available the needed products are 
likely unobtainium.  So pick when _might_ be found in an electronics grave site.

**Comment by hsoft** [comment]
The wiki of this project is editable by anyone. Maybe it would be appropriate to create a wiki page with that kind of information?

**Comment by Allisontheolder** [comment]
Works, when I get a chance the hardware will be spun off to its own.
Code tested and its a viable wa to load and go.
