### ISSUE TITLE
make does not work

### ISSUE THREAD

**Issue by frivermen** [hsoft/collapseos#79]
Two weeks ago, I was able to build an emulator.
But now `make` hangs on the line
`../zasm.sh -o 07 ../../kernel shell/user.h ../../apps < ../../apps/shell/glue.asm | tee shell/shell.bin > /dev/null`
Has anyone else come across this?

**Comment by hsoft** [comment]
It generally happens when you play around and break your bootstrap binaries (kernel.bin, zasm.bin). Does your git status tell your they're modified? Then reset them and run `make clean all`. It should set things right.

**Comment by frivermen** [comment]
Я переустанавливал систему пару дней назад. Поэтому скачивал всё заново. Такая проблема с оригинальными файлами.

**Comment by Redlolz** [comment]
What OS are you using to build CollapseOS?

**Comment by hsoft** [comment]
I doubt its an OS problem. If it was, there would be a problem building the tooling around the emulator. This is typically a symptom of messed up bootstrap binaries.

@frivermen even if your repo is fresh, it's easy to mess binaries without noticing. Do it again, at the root of the collapse os project:

```
git reset --hard
git clean -fxd
cd tools/emul
make
```

**Comment by frivermen** [comment]
My OS is Manjaro 64 bit XFCE. I also tried on another computer, Manjaro 32 bit XFCE. Other projects have been successfully assembled. Only this one cannot.

**Comment by QuercusFelis** [comment]
I'm running an arch based distro and was able to compile just fine. I don't think your distro is the problem.
