### ISSUE TITLE
Basic as a shell

### ISSUE THREAD

**Issue by hsoft** [hsoft/collapseos#80]
For those who've been following recent commits, you'll see that I'm on track to replace the shell with the new basic interpreter. I know, it's not a new idea: that's even the default shell on the RC2014.

However, the way I'm envisioning this is to supercharge that interpreter with hooks in the system making it a very potent and efficient sysadmin tool. The idea is that you build yourself little tools in assembler and then use those little tools in the interpreter, which becomes the tools' glue.

I know, It was already possible, but the way I'm planning things, I'm going to make it convenient.

I already know a little bit where I'm going, but if someone as ideas, suggestions, I'm opening this issue.

**Comment by octave-syndicate** [comment]
I really like the idea of BASIC as default high-level language and script to glue components together and admin the system.

**Comment by Redlolz** [comment]
I really like it too since a lot of people already know BASIC, and if they don't it's relatively easy to learn.
