### ISSUE TITLE
Create recipe stub for Z80-MBC2

### ISSUE THREAD

**Issue by octave-syndicate** [hsoft/collapseos#82]
I'm posting this as an issue to get feedback before I pull the trigger on a PR for just a stub recipe for the Z80-MBC2. Although this won't be terribly useful I want to be able to advocate to existing Z80-MBC2 communities to contribute to CollapseOS and believe having a link pointing directly to where such contributions should manifest might be helpful.

I have a fully-assembled Z80-MBC2 but am not at the point where I can contribute much more to the recipe. My next step is to buy a soldering station, multimeter, and Z80-MBC2 kit to teach myself a bit about assembling such hardware using the working, assembled board as a reference. Once complete I'll spend some time doing some EEPROM programming. Baby steps.

**Comment by f4grx** [comment]
Cool board, a bit complex because of the Atmega used for IO/EPROM and how it uses DMA requests, but that's a nice system!

**Comment by hsoft** [comment]
AVR and Z80 go well together. I wonder if it will be possible, once the avr assembler is done, to reprogram the atmega32 in-place...

**Comment by octave-syndicate** [comment]
> AVR and Z80 go well together. I wonder if it will be possible, once the avr assembler is done, to reprogram the atmega32 in-place...

It does seem like a win-win in the long run and I like that this board is "open source" and you can download the kicad and gerber files for everything. That doesn't seem to be the case for the RC2014 but on the other hand I think it's probably a better design for learning by not relying on the atmega32 for a lot of functionality...at least that's what my friends who graduated from the EE department tell me. :)

**Comment by f4grx** [comment]
for the next supported hardware, you can tackle this one: http://www.chrisfenton.com/the-zedripper-part-1/

:)

**Comment by octave-syndicate** [comment]
Not eating out at restaurants lately has left me with a bit more disposal income than usual. :) 

If it will help with this port I can ship you the Z80-MBC2 hardware (assembled) direct from Italy. 

https://shop.mcjohn.it/en/diy-kit/22-33-kit-z80-mbc2.html#/13-kit-assembled

**Comment by hsoft** [comment]
Thanks for the offer, I'll take it! I wouldn't mind the disassembled version, I like assembling this stuff, but it is a bit time consuming...

It will be my next target after I'm done making the Forth branch on-par with `master` (so I can replace it). You have one yourself for testing?

PM-ing you my address on IRC.

**Comment by octave-syndicate** [comment]
I do have one for testing! It works fine with the included USB RS232-TTL or equivalent but if you'd prefer the uTerm or UCom let me know and I'll include the assembled version in the order :

https://shop.mcjohn.it/en/diy-kit/24-35-kit-uterm.html#/13-kit-assembled

https://shop.mcjohn.it/en/diy-kit/25-37-kit-ucom.html#/13-kit-assembled

**Comment by hsoft** [comment]
TTL is fine. That uTerm page made be land on ChibiTerm, which is interesting. A good reason to have an ARM assembler in Collapse OS.

**Comment by hsoft** [comment]
... which leads to http://geoffg.net/terminal.html which is even more interesting. I didn't know about those projects.

**Comment by octave-syndicate** [comment]
Hi Virgil. The order has been placed for the Z80-MBC2 to be shipped to the address you provided. I'll send along a copy of the invoice via email to your address on record for your github @hsoft account.

**Comment by octave-syndicate** [comment]
@f4grx It's a super nice system to work with as a hardware novice and, believe me, I'm very qualified to offer this perspective! :o) You can also purchase it with assembled and connected ps/2, vga, rs-232 interface or a more simple RS-232 terminal interface. I have some hope CollapseOS could be included with the device software library at some point once Virgil thinks its wise to move in such a direction. In any case, highly recommended!

**Comment by octave-syndicate** [comment]
@hsoft Hi Virgil. Z80-MBC2 has been shipped. I forwarded the tracking info/link to the email address associated with your github profile.

**Comment by hsoft** [comment]
I've just received it, thanks. The timing isn't bad: I'm nearly finished with my 8086 PC/AT port, I'll have time to play with it.

**Comment by hsoft** [comment]
Bullseye on first try! I look a bit at CRT0's code, implement a tentative `(emit)` and `(key)`, copy to `autoboot.bin`, and we have Collapse OS!

**Comment by hsoft** [comment]
The `z80mbc2` recipe is now done.

**Comment by octave-syndicate** [comment]
Super cool! I posted a link to the recipe on the Z80-MBC2 Facebook group. I'll probably also advocate for it to be included by default in the next IOS release if the opportunity presents itself.

**Comment by hsoft** [comment]
If it's going to be included in the SD image, we might as well go the extra mile and add GPIO drivers to the recipe, it would make it much more useful.

**Comment by hsoft** [comment]
That a hint to you, @octave-syndicate :) if you look at the driver code, you'll see that all I do is to poke the ports according to the protocol described in the .ino source of IOS. This can be done in pure Forth.

**Comment by octave-syndicate** [comment]
Hint has been duly noted!

**Comment by SuperFabius** [comment]
Hi, I'm the designer of the Z80-MBC2.
Now Collapse OS is supported by the IOS:
![Screenshot](https://i.postimg.cc/25qmmVyH/Screenshot-20200624-134613.png)

The new IOS and SD image will be soon available...

Regards.

J4F

**Comment by SuperFabius** [comment]
New IOS and SD image supporting Collapse OS are out [here](https://hackaday.io/project/159973-z80-mbc2-a-4-ics-homebrew-z80-computer#menu-files).

BTW: After the blk.fs filesystem generation I've "expanded" the emulated disk to 8MB (the full size of an IOS emulated disk) using  0x00 as filler. This because the IOS disk emulation can't change the size of the "disk file" on the SD, so it would have been impossible to add new "records".
