### ISSUE TITLE
Localisation, for example for Polish language

### ISSUE THREAD

**Issue by nastepnym** [hsoft/collapseos#83]
Where I can download font, information, translate messages in my lang?

**Comment by hsoft** [comment]
Collapse OS is not multilingual. I don't want to add that complexity. I'm not sure how to approach the problem, but so far, my guess is that following blackout (collapse of internet infrastructure), local engineers will be able to translate their local "final" copies of Collapse OS into their local language before they die (it's not unreasonable to assume that their successors will be unlikely to know english).

Alternatively, at some point, Collapse OS will be considered "done" and then it might be reasonable to spawn localized copies of it.

But as long as it's in active development, I don't think localization efforts are worth it. It will be too much effort to keep localized copies in sync with new developments.
