### ISSUE TITLE
No keyboard exit condition in documentation

### ISSUE THREAD

**Issue by Izder456** [hsoft/collapseos#88]
I would like to be able to exit binarys with maybe ctrl+c/x like in unix. Or esc or something along those lines. I could not find this in the documentation.

**Comment by hsoft** [comment]
There's only one interactive application, `ed` and its exit command is documented.

The BASIC shell isn't designed to be quit from, but if you mean quit the emulator, then it's CTRL+D. I thought it was documented, but it appears that it is not.

**Comment by Izder456** [comment]
Thanks I guess I should of looked more closely in the docs. Anyways looks like the command `system` would do it.
