### ISSUE TITLE
Unable to get simple example working

### ISSUE THREAD

**Issue by Junkotron** [hsoft/collapseos#90]
Compiled a newly cloned version of collapseos and tried to run the example in doc/zasm.md
Got this:

$ ./shell/shell 
Initializing filesystem from cfsin
Collapse OS
> fnew 1 dest
> fopen 0 hello.asm
> fopen 1 dest
> zasm 1 2
ERR
> dest
ERR
> 

Trying the same things on the javascript web emulator works

/Erik

**Comment by hsoft** [comment]
You're right, it seems that zasm is broken in the emulated shell. I'll look into it shorty, thanks for the heads up.

**Comment by hsoft** [comment]
@Junkotron it should work now. Make sure to rebuild `cfsin/zasm`.

Your `collapseforth` repo looks promising!

**Comment by Junkotron** [comment]
Awesome will try it tomorrow

Sent from ProtonMail mobile

-------- Original Message --------
